/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // VitaLink Brand Colors
        teal: {
          DEFAULT: "#17A2B8",
          50: "#F0F9FB",
          100: "#E0F2F7",
          200: "#B3DFE9",
          300: "#80CADC",
          400: "#4DB5CE",
          500: "#17A2B8",
          600: "#0D8FA8",
          700: "#0A7A93",
          800: "#08667F",
          900: "#065270",
        },
        cyan: {
          DEFAULT: "#1DD1E1",
          50: "#F0FCFD",
          100: "#E0F9FB",
          200: "#B3F0F6",
          300: "#80E7F2",
          400: "#4DDEEE",
          500: "#1DD1E1",
          600: "#16B7C9",
          700: "#119DB3",
          800: "#0D839D",
          900: "#096987",
        },
        orange: {
          DEFAULT: "#FF8C42",
          50: "#FEF7F0",
          100: "#FDEEE0",
          200: "#FBDCC0",
          300: "#F8C4A0",
          400: "#F5A860",
          500: "#FF8C42",
          600: "#E87B2D",
          700: "#D16A1A",
          800: "#B85B14",
          900: "#9F4C0F",
        },
        // Legacy color aliases for backward compatibility
        royal: {
          DEFAULT: "#1E1B8F",
          50: "#EEF0FC",
          100: "#D9DDF9",
          200: "#B3BBF3",
          300: "#8D99ED",
          400: "#6777E7",
          500: "#4145E1",
          600: "#2D2B9F",
          700: "#1E1B8F",
          800: "#161380",
          900: "#0E0C70",
        },
        gold: {
          DEFAULT: "#D4AF37",
          50: "#FCF9EF",
          100: "#F9F2DC",
          200: "#F4E4A6",
          300: "#ECD66F",
          400: "#E3C848",
          500: "#D4AF37",
          600: "#B5932E",
          700: "#967725",
          800: "#775B1C",
          900: "#583F13",
        },
      },
      borderRadius: {
        "3xl": "28px",
        "2xl": "24px",
        xl: "20px",
        lg: "16px",
        md: "12px",
        sm: "8px",
        xs: "6px",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        soft: "0 2px 8px rgba(13, 107, 125, 0.08)",
        card: "0 8px 24px rgba(13, 107, 125, 0.12)",
        glass: "0 8px 32px rgba(13, 107, 125, 0.15)",
        floating: "0 12px 40px rgba(13, 107, 125, 0.2)",
        "glow-teal": "0 0 20px rgba(23, 162, 184, 0.3)",
        "glow-cyan": "0 0 20px rgba(29, 209, 225, 0.3)",
        "glow-orange": "0 0 20px rgba(255, 140, 66, 0.3)",
        "glow-gold": "0 0 20px rgba(255, 140, 66, 0.3)",
        "glow-blue": "0 0 20px rgba(13, 107, 125, 0.2)",
        premium: "0 4px 16px rgba(13, 107, 125, 0.1), 0 16px 48px rgba(13, 107, 125, 0.08)",
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', 'sans-serif'],
        mono: ['SF Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '1.1', fontWeight: '700' }],
        'h1': ['36px', { lineHeight: '1.2', fontWeight: '600' }],
        'h2': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'h3': ['22px', { lineHeight: '1.3', fontWeight: '600' }],
        'h4': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "nfc-ripple": {
          "0%": { transform: "scale(0.8)", opacity: "1" },
          "100%": { transform: "scale(2)", opacity: "0" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "page-fade-in": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-subtle": {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.05)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "glow": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(212, 175, 55, 0.3)" },
          "50%": { boxShadow: "0 0 40px rgba(212, 175, 55, 0.5)" },
        },
        "slide-in-right": {
          from: { transform: "translateX(100%)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "slide-out-right": {
          from: { transform: "translateX(0)", opacity: "1" },
          to: { transform: "translateX(100%)", opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "nfc-ripple": "nfc-ripple 1.5s ease-out infinite",
        "shimmer": "shimmer 1.5s infinite",
        "page-fade-in": "page-fade-in 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
        "pulse-subtle": "pulse-subtle 2s ease-in-out infinite",
        "float": "float 3s ease-in-out infinite",
        "glow": "glow 2s ease-in-out infinite",
        "slide-in-right": "slide-in-right 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
        "slide-out-right": "slide-out-right 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
